wip: pkb follows
wvffle/ATS-project-simple pull request #15
Opened 2023-04-02 18:57 UTC by KamiloSzcz

Dodany został follow

2023-04-02 19:06 UTC, wvffle requested changes
Brakuje testow.

2023-04-02 19:06 UTC, wvffle commented on ats/pkb/follows.py
> +def follows(list):
W jaki sposob query evaluator ma wywolac te funkcje dla zapytania:

```
stmt s1, s2;
Select s1 such that Follows(s1, s2);
```

2023-04-02 19:06 UTC, wvffle commented on ats/pkb/follows.py
> +                        return True
To sprawdza tylko i wylacznie czy w drzewie wystepuja dwa statementy pod rzad

2023-04-02 19:06 UTC, wvffle commented on ats/pkb/follows.py
> +
zbedny import

2023-04-02 19:06 UTC, wvffle commented on ats/pkb/follows.py
> +                        # return child.children[i:i+2]
zbedne komentarze

2023-04-02 19:06 UTC, wvffle commented on main.py
> +    # parents.parents(tree)
zbedny komentarz

2023-04-02 19:11 UTC, wvffle requested changes
Co dodaje ten commit? Patrze sie na historie commitow i nie mam pojecia. Musze sprawdzic. Jezeli zmiennych nie nazywasz `a`, `b`, `c` to commitow tez tak nie nazywaj. Wiadomosc w commicie jest wlasnie po to by osoba sprawdzajaca pozniej kod lub szukajaca ktory commit w czyms zawinil wiedziala mniej wiecej co commit robi.

2023-04-02 19:11 UTC, wvffle commented on ats/pkb/parents.py
> +def parent(list):
To samo, jak query preprocessor ma sie do tego odwolac przy analogicznym zapytaniu jak w `follows.py`

2023-04-02 19:11 UTC, wvffle commented on ats/pkb/parents.py
> +def parent(list):
Po co rozbijasz na dwa pliki? Obie funkcje moga byc w jednym module

2023-04-02 19:11 UTC, wvffle commented on ats/pkb/parents.py
> +                return False
To sprawdza jedynie czy istnieje stmtLst, ktory ma dzieci, A ISTNIEJE bo taki jest wymog specyfikacji

2023-04-02 20:18 UTC, KamiloSzcz commented
Commit dodał funkcje Follows i parents w jednym pliku
Wpisując  odpowiednie wartości dla s1 i s2 odnajduje się taką sytuacje
i zwaracana jest wartosc boolen
pliki follows.py i parents.py są do usunięcia

2023-04-02 20:41 UTC, wvffle commented
> pliki follows.py i parents.py są do usunięcia

To je usun.

Rowniez: https://github.com/wvffle/ATS-project-simple/pull/15#pullrequestreview-1368129272

2023-04-03 06:41 UTC, wvffle commented
Spytam sie inaczej... Co oznacza `pkb` w wiadomosci commita? Patrzac na [historie Twoich commitow](https://github.com/wvffle/ATS-project-simple/pull/15/commits) nie mam pojecia... Patrzac sie na [historie commitow w masterze](https://github.com/wvffle/ATS-project-simple/commits/master) wszystko jest logiczne i wiadomo o co chodzi...

Jeszcze raz odsylam do  https://github.com/wvffle/ATS-project-simple/pull/15#pullrequestreview-1368129272

2023-04-03 11:28 UTC, SiwyKot41 requested changes

2023-04-03 11:28 UTC, SiwyKot41 commented on ats/pkb/pkb.py
> +def follows(list, s1, s2):
Skąd pisząc zapytanie PQLowe mam wiedzieć o odpowiednich wierzchołkach drzewa? Przecież ja jedynie mam do dyspozycji zmienne i stałe (`stmt s1, s2;`, czy `1`).

Te funkcje pomimo tego, że nie dałeś typu zmiennych przyjmują wierzchołki drzewa... Powinny przyjmować stringi...

2023-04-03 11:28 UTC, SiwyKot41 commented on ats/pkb/pkb.py
> +    while pool:
Wpierw powinniście zrobić sobię mapę statementów a następnie się do niej odwoływać kiedy np. proszę o statement numer 1 
```
statements = {
  1: <StmtNode>,
  2: <StmtNode>,
  ...
}
```

2023-04-03 11:28 UTC, SiwyKot41 commented on ats/pkb/pkb.py
> +                return False
To wszystko można sprawdzić po prostu porównując indeksy `stmtLst.nodes.statements.index(s1) + 1 == stmtLst.nodes.statements.index(s2)`

2023-04-03 16:54 UTC, wvffle requested changes

2023-04-03 16:54 UTC, wvffle commented on ats/parser/utils.py
>  import re
Cos skopaliscie z historia commitow, ze macie commity z #16. Naprawcie to

2023-04-03 16:54 UTC, wvffle commented on ats/pkb/pkb.py
> +        if "stmt:" in child.str():
Nie sprawdziajcie po nazwie, tylko po rzeczywistym typie. `isinstance(child, nodes.StmtNode)`

2023-04-04 14:05 UTC, closed without merging