feat: add pkb
wvffle/ATS-project-simple pull request #19
Opened 2023-04-04 14:04 UTC by KamiloSzcz

2023-04-21 20:56 UTC, wvffle requested changes
Powinniscie miec zmienna `statements`, gdzie przechowujecie numer statementu jako klucz, a node z drzewa AST jako wartosc. Wyrzuciliscie ten kawalek kodu z jakiegos powodu.

2023-04-21 20:56 UTC, wvffle commented on ats/pkb/pkb.py
> +            return "Wrong query!"
tu ma byc wywolanie funkcji `process_query`, wiec przeniescie to do niej

2023-04-21 20:56 UTC, wvffle commented on ats/pkb/pkb.py
> +            return "Wrong query!"
nie return, tylko `raise ValueError("<tresc bledu>")` z dobrze opisujaca bled trescia

2023-04-21 20:56 UTC, wvffle commented on ats/pkb/pkb.py
> +                i
czym jest i?

2023-04-21 20:56 UTC, wvffle commented on ats/pkb/pkb.py
> +                for j, i in follows_dictionary.items()
czym jest i, czym jest j?

2023-04-21 20:56 UTC, wvffle commented on ats/pkb/pkb.py
> +        for i in range(len(node.children)):
```suggestion
        for child in node.children:
```

2023-04-21 20:56 UTC, wvffle commented on ats/pkb/pkb.py
> +            childrens.append(node.children[i])
tak na prawde na L17 mogliscie dac `children = node.children`, wyszloby na to samo

2023-04-21 20:56 UTC, wvffle commented on ats/pkb/pkb.py
> +        childrens = []
```suggestion
        children = []
```

2023-04-21 20:56 UTC, wvffle commented on ats/pkb/pkb.py
> +        if len(node.children) > 0:
ten warunek nie bedzie spelniony tylko dla `ConstantNode` i `VariableNode`, cala reszta bedzie miala dzieci

2023-04-21 20:56 UTC, wvffle commented on ats/pkb/pkb.py
> +            parent_childrens_list.insert(0, childrens)
Czemu akurat tak? Nie rozumiem. Ten kawalek kodu wykonuje sie jak konczycie obrobke konkretnego node i chcecie wyjsc wyzej. Mieszaja wam sie totalnie indeksy teraz. Zalozmy taki przypadek:
```
    stmt   
   /    \
stmt    stmt
```

Poprawnie ponumerowany powinien wygladac tak:

```
     stmt1
    /     \
stmt2     stmt3
```
Tak sie sklada, ze to jest dokladnie taka sama numeracja jak kolejnosc z jaka wchodzicie do nodeow uzywajac DFSa.

Natomiast ta linijka sprawia, ze numerujecie je tak:

```
     stmt1
    /     \
stmt3     stmt2
```

2023-04-21 20:56 UTC, wvffle commented on ats/pkb/pkb.py
> +    parent_childrens_list = []
```suggestion
    parent_children_list = []
```

2023-04-21 20:56 UTC, wvffle commented on ats/pkb/pkb.py
> +            for j in range(len(parent_childrens_list[i]) - 1):
O(n^2)

2023-04-21 20:56 UTC, wvffle commented on ats/pkb/pkb.py
> +                    == str(parent_childrens_list[i][j + 1]).split(": ")[0]
Juz wczesniej komentowalem. Nie porownujcie typow przez sprawdzanie ich nazwy. Kazdy typ nodea ma swoja wlasna klase. Uzywajcie `isinstance`

2023-04-21 20:56 UTC, wvffle commented on ats/pkb/pkb.py
> +                    )
Dlaczego jako klucze macie np `stmt: assign` a jako wartosc macie np `stmt: if`. Co wam to da? Finalnie macie przeciez zwrocic numerek statementu a nie jego graficzna reprezentacje w drzewie AST

2023-04-21 21:18 UTC, wvffle commented
Dla samego przykladu na jakim pracujecie zwracacie zle wyniki:
![image](https://user-images.githubusercontent.com/13330620/233736153-5343806d-f779-4e53-995b-f34a694f38e1.png)
Powinniscie zwrocic while, assign na prawo od while i assign na prawo od ifa

2023-04-21 21:27 UTC, wvffle commented
Wpierw dodajcie testy i zaprojektujcie jak to ma dzialac, a dopiero potem to implementujcie.....

2023-04-22 09:59 UTC, MParchan commented
Jeśli chodzi o wyniki to są poprawne, bo jak mamy zapytanie "stmt s1, s2; Select s1 such that Follows(s1, s2)" to mamy wybrać statementy bezpośrednio po których występuje inny statement

2023-04-22 14:45 UTC, wvffle commented
> to mamy wybrać statementy bezpośrednio po których występuje inny statement

Jezeli tak, to po prostu wybraliscie zbyt maly przyklad. Dodajcie sobie jeszcze kilka ifow, while i assignow i zobaczycie ze szybko wam sie rozjedzie

2023-04-22 15:31 UTC, MParchan commented
Wydaje mi się że w obecnej formie poradził by sobie z kazdym przypadkiem ale jest to na razie wstępna wersja bo trzeba będzie poprawić format słownika i złożoność jego tworzenia.

2023-04-22 20:05 UTC, wvffle commented
> Wydaje mi się że w obecnej formie poradził by sobie z kazdym przypadkiem

```
procedure proc {
  a = 1;
  a = 1;
  a = 1;
  a = 1;
}
```

Powinno zwrocic 3 wyniki.


Tlumaczylem to juz @KamiloSzcz, wpierw napiszcie testy, pozniej dopiero robcie implementacje.

2023-05-10 19:02 UTC, wvffle requested changes

2023-05-10 19:02 UTC, wvffle commented on ats/pkb/pkb.py
> +            # 2 - constant and variable
```suggestion
            # case 2 - constant and variable
```

2023-05-10 19:02 UTC, wvffle commented on ats/pkb/pkb.py
> +            # 2 - constant and variable
```suggestion
            # case 2 - constant and variable
```

2023-05-11 07:26 UTC, wvffle requested changes

2023-05-11 07:26 UTC, wvffle commented on ats/pkb/pkb.py
> +                current_node = current_node.parent
Wywalcie, chcialem mergowac, a musze teraz sprawdzac....

2023-05-11 07:26 UTC, wvffle commented on ats/pkb/pkb.py
> +    return results
wywalcie

2023-05-15 22:27 UTC, wvffle commented
Przypominam, ze nie moge zmergowac bo testy nie maja 100% pokrycia

https://app.codecov.io/gh/wvffle/ATS-project-simple/pull/19/blob/ats/pkb/pkb.py

2023-05-16 17:24 UTC, KamiloSzcz commented on tests/pkb/test_follows.py
> +"""
Nie potrzebne. Już jest to usunięte

2023-05-16 17:24 UTC, KamiloSzcz commented on ats/pkb/pkb.py
> +    print(parent)
Już jest to usunięte

2023-05-16 17:24 UTC, KamiloSzcz commented on ats/pkb/pkb.py
> +                print(parent[stmt.__stmt_id])
Już jest to usunięte.

2023-05-16 18:51 UTC, wvffle approved these changes

2023-05-16 19:06 UTC, merged