feat(pql): add multiple 'and' for relations and withs
wvffle/ATS-project-simple pull request #21
Opened 2023-05-03 10:46 UTC by SiwyKot41

2023-05-03 16:18 UTC, wvffle requested changes

2023-05-03 16:18 UTC, wvffle commented on ats/pql/pql.py
> +        if relationship == "Modifies" or relationship == "Uses":
wydziel do arraya

2023-05-03 16:18 UTC, wvffle commented on ats/pql/pql.py
> +            or relationship == "Follows*"
wydziel do arraya

2023-05-03 16:18 UTC, wvffle commented on ats/pql/pql.py
> +        elif relationship == "Calls" or relationship == "Calls*":
wydziel

2023-05-03 16:18 UTC, wvffle commented on ats/pql/pql.py
> +            parameters = process_calls(variables)
w ogole wydziel do oddzielnej funkcji

2023-05-03 16:18 UTC, wvffle commented on tests/pql/test_calls.py
> +    with pytest.raises(ValueError, match="""Variable '90' is not valid ENTREF_TOKEN"""):
90 to nie zmienna

2023-05-03 16:18 UTC, wvffle commented on tests/pql/test_calls.py
> +    assert result[0]["relations"][0]["parameters"][1] == '"cuatro"'
czemu to zwraca quote w stringu?

2023-05-03 16:18 UTC, wvffle commented on tests/pql/test_calls.py
> +    with pytest.raises(ValueError, match="""Variable '90' is not valid ENTREF_TOKEN"""):
czemu uzywasz multiline stringa?

2023-05-03 16:18 UTC, wvffle commented on tests/pql/test_follows.py
> +    assert result[0]["relations"][0]["parameters"][0] == "'_'"
zastanawiam sie czy to nie powinno zwracac np: `None` albo jakiegos konkretnego obiektu do ktorego pozniej mozna sie porownywac

2023-05-03 16:18 UTC, wvffle commented on tests/pql/test_modifies.py
> +        ValueError, match="Token 'Modifies\\*' is not a valid NAME_TOKEN"
czemu escape?

2023-05-03 16:38 UTC, SiwyKot41 commented on ats/pql/pql.py
> +            if relationship == "Modifies" or relationship == "Uses":
Ale tu są tylko dwie możliwe opcje więc po co to do listy dawać, tylko modifies i uses nie mają *

2023-05-03 16:41 UTC, SiwyKot41 commented on tests/pql/test_calls.py
> +    with pytest.raises(ValueError, match="""Variable '90' is not valid ENTREF_TOKEN"""):
potrzebowałem go w innym miejscu, i nie zmienialem tego bo działa tak samo

2023-05-04 07:46 UTC, wvffle commented on ats/pql/pql.py
> +            if relationship == "Modifies" or relationship == "Uses":
by bylo jedno miejsce gdzie mozesz to szybko zmodyfikowac

2023-05-04 07:47 UTC, wvffle commented on ats/pql/pql.py
> +    def match_entref_token(variables):
czy entRef

2023-05-04 07:48 UTC, wvffle commented on tests/pql/test_calls.py
> +    with pytest.raises(ValueError, match="""Variable '90' is not valid ENTREF_TOKEN"""):
ale tu nie potrzebujesz

2023-05-05 00:30 UTC, wvffle requested changes

2023-05-05 00:30 UTC, wvffle commented on ats/pql/pql.py
> +    pass
```suggestion
class AnyType:
    def __repr__(self):
      return self.__str__()
      
    def __str__(self):
      return 'Any'
      
Any = AnyType()
```

2023-05-05 00:30 UTC, wvffle commented on ats/pql/pql.py
> +    relationships_ent_ref_and_ent_ref = ["Calls", "Calls*"]
jako globalne zmienne i uppercase

2023-05-05 00:30 UTC, wvffle commented on ats/pql/pql.py
> +        nonlocal relationships_without_star
nie potrzebujesz jak nie modyfikujesz

2023-05-05 00:30 UTC, wvffle commented on ats/pql/pql.py
> +            raise ValueError(f"Token '{current_token}' is not valid ATTRNAME_TOKEN")
```suggestion
            raise ValueError(f"Token '{current_token}' is not valid ATTR_NAME_TOKEN")
```

2023-05-05 00:30 UTC, wvffle commented on ats/pql/pql.py
> +        nonlocal relationships_ent_ref_and_ent_ref
```suggestion
```

2023-05-16 16:45 UTC, wvffle requested changes

2023-05-25 19:22 UTC, wvffle requested changes

2023-05-25 19:22 UTC, wvffle commented on tests/pql/test_follows.py
> +    assert repr(anything) == "Any"
Tego nie zmieniles jeszcze

2023-05-25 19:26 UTC, wvffle commented
@SiwyKot41: Jakbys mogl rozwiazac konflikty to by bylo super

2023-05-26 18:37 UTC, wvffle commented
No chlopie, ani to nie jest zlintowane, ani .exe sie nie zbudowal ani testow to teraz nie przechodzi. Revertnij te dwa commity i zrob to porzadnie.

2023-05-26 18:37 UTC, wvffle requested changes

2023-05-26 18:37 UTC, wvffle commented on ats/pql/pql.py
> +def parse_pql(text: str):
```suggestion
def parse_query(text: str):
```

2023-05-31 09:33 UTC, wvffle approved these changes

2023-05-31 09:34 UTC, merged